name: sample
on:
 workflow_dispatch:

jobs:
  build:
    runs-on:
       -self-hosted
    
    steps:
      - uses: actions/checkout@v2

      - name: run a one-line sctipt
        run: |
           echo " Hello Nanda"
           sleep 10
      - name : run mult-line
        run: |
            echo "{{ github.workspace }}"
